// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadSettings():Promise<main.Settings>;

export function ResetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.SettingsPatch):Promise<main.Settings>;
