// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;
export function LoadSettings():Promise<{apiBaseUrl: string; authMode: "password" | "api_token"; apiToken?: string; requestTimeoutSeconds: number;}>;
export function SaveSettings(arg1:{apiBaseUrl?: string; authMode?: "password" | "api_token"; apiToken?: string; requestTimeoutSeconds?: number;}):Promise<{apiBaseUrl: string; authMode: "password" | "api_token"; apiToken?: string; requestTimeoutSeconds: number;}>;
export function ResetSettings():Promise<{apiBaseUrl: string; authMode: "password" | "api_token"; apiToken?: string; requestTimeoutSeconds: number;}>;
